front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /plateforme

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"