# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_SUPER_ADMIN, ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
                success_handler: app.redirect_after_login
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: /logout
                target: /
                success_handler: app.redirect_after_logout
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/back_office/, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }

